### ISSUE TITLE
cooLMS takes you to file index, not homepage

### ISSUE THREAD

**Issue by jennyhottle** [xtai/INST-728z-Final-Project#17]
will address this later

**Comment by xtai** [comment]
@jennyhottle, this is probably a local environment configuration issue, you can try to run a local web server to solve this; I use this: [browsersync](https://www.browsersync.io/).

btw, just fixed a permission issue on the server.

**Comment by xtai** [comment]
This might still be an issue since we are submitting our code through a zip file. I'll fix this later.
